# 1. Image Node
FROM node:20-alpine

# 2. Working directory
WORKDIR /app

# 3. Copy package files
COPY package*.json ./

# 4. Install dependencies
RUN npm install

# 5. Copy source code
COPY . .

# 6. Build NestJS
RUN npm run build

# 7. Expose port
EXPOSE 3000

# 8. Run app
CMD ["npm", "run", "start:prod"]
